server:
  port: 5000
  address: localhost
  use-forward-headers: true
spring:
  profiles:
    active: production
  resources:
    add-mappings: false
  datasource:
    password:
    username: sa
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: create
db:
  tenantSchemaName: TENANTS
cognito:
  clientId: ${COGNITO_CLIENT_ID}
  region: ${COGNITO_REGION}
  poolId: ${COGNITO_USER_POOL_ID}